### PR TITLE
moved to CrossBuild + sclaajs-0.6-RC2 support

### PR DESCRIPTION
**Pull request by antonkulaga**
Moved sbt configuration to CrossProject and scalajs-0.6-RC2
Dropped 2.10 support as most of scala and scala-js libraries now compile to 2.11 and crossbuilding to 2.10 does nothing useful
Updated version nubmer

### CODE REVIEW

**Comment by benhutchison** [comment]
Scala 2.10 support was provided by @ddispaltro. Reluctant to drop it if he still needs it (?) and 2.12 isnt out.

**Comment by antonkulaga** [comment]
If @ddispaltro still needs 2.10 I can bring it back to this my PR when I will find time for this

**Comment by antonkulaga** [comment]
I returned crosscompilation to 2.10, could you look now?

**Comment by benhutchison** [comment]
@antonkulaga I will be able to review/test/respond by the end of the week. Busy at work ATM.

**Comment by ddispaltro** [comment]
I am fine if it goes away.  Thanks for remembering though!


-Dan

**Comment by benhutchison** [comment]
@antonkulaga Ive looked over the changes in some detail and they are pretty cool. I like the crossproject concept and the travis build. I just need to find some time to test it out thoroughly before merging. Will drop 2.10 support.

**Comment by benhutchison** [comment]
Thanks :)

**Pull request merged**
