### PR TITLE
Allow pickling even for a type which is not a class, if an implicit pickler exists

### PR DESCRIPTION
**Pull request by Gralfim**
Allow pickling even for a type which is not a class, if an implicit pickler exists
#37

### CODE REVIEW

**Comment by benhutchison** [comment]
Please add a unit test for the use case

**Comment by benhutchison** [comment]
Hi @Gralfim thanks for the test. 

However I would like the `TestVectorData` simplified down to the bare essentials required to express your usage. Ie some pattern that another user of the library could recognize and map onto their problem. 

I wonder, is that simply that it can summon a `Pickler`/`Unpickler` for an aliased type? in which case, couldn't you just have 
```
case class MyVector(val x: Float)
type Vector = MyVector
```
at the top of the test and have captured the essentials?

**Comment by Gralfim** [comment]
We tried to simplify the test as much as possible. Unfortunately, it cannot be as easy as your proposal. In your case, the compiler knows that Vector is a class:
```
        case class MyVector(val x: Float)
        type Vector = MyVector
        case class Model(v: Vector)

        val original = Model(new Vector(1))
        val json = Pickle.intoString(original) // compiles even prior our change
        val actual = Unpickle[Model].fromString(json).get
        assert(actual == original)

```

**Comment by benhutchison** [comment]
LGTM, thanks @Gralfim !

I understand your situation properly now. Quite a subtle problem, I admit closing #37 was premature.

**Pull request merged**
